### ISSUE TITLE
Issue in "codenvy/php"

### ISSUE THREAD

**Issue by freewind** [codenvy/dockerfiles#30]
https://github.com/codenvy/dockerfiles/blob/master/php/ubuntu/Dockerfile#L24

```
RUN sudo sed -i 's/\/var\/www\/html/\/projects/g'  /etc/apache2/sites-available/000-default.conf && \
 ```

There is no `sites-available/000-default.conf` in file system for now, instead, it's `sites-enabled/000-default.conf`

**Comment by freewind** [comment]
see this PR: https://github.com/codenvy/dockerfiles/pull/32

**Comment by TylerJewell** [comment]
This issue is resolved - so closing.
