### ISSUE TITLE
Shall we create a stack for just html/frontend projects?

### ISSUE THREAD

**Issue by freewind** [codenvy/dockerfiles#33]
I see there is a `node` stack which includes a lot of node related packages, but no http servers (e.g. `apache2`) included.

I wonder if we could create a new stack for html/frontend projects, that it has a http server started, and we can run `bower` commands in terminal?

Although I can create such a recipe for myself, but I just think it might be a common case

**Comment by TylerJewell** [comment]
We will need to create a variety of stacks like this.  We wanted to target such work for the GA in March but if it is something needed sooner we will take pull requests on the /Codenvy/dockerfiles repository.  Commits there will show up within the distribution.
